refactor sdk
assetcrush/reactjs-sdk pull request #3
Opened 2022-04-04 16:58 UTC by ali-718

2022-04-04 18:16 UTC, fawaz-ahmed commented on README.md
> +      <ImageCrush onLoad={onLoad} onError={onError} url={testUrl} width={50} height={50} />
Add on load and on error only in props table

2022-04-04 18:27 UTC, fawaz-ahmed requested changes
See comments. Fade in still to decide

2022-04-04 18:27 UTC, fawaz-ahmed commented on README.md
> +      <ImageCrushAdoptive onLoad={onLoad} onError={onError} url={testUrl} />
Same here

2022-04-04 18:27 UTC, fawaz-ahmed commented on README.md
> +        onLoad={onLoad}
Same here

2022-04-04 18:27 UTC, fawaz-ahmed commented on example/src/modules/ImageCrush.js
> +  const handleError = (e) => {
Use callback

2022-04-04 18:27 UTC, fawaz-ahmed commented on example/src/modules/ImageCrush.js
> +  const handleRetry = () => {
Use callback

2022-04-04 18:27 UTC, fawaz-ahmed commented on example/src/modules/ImageCrush.js
> +
Use calback

2022-04-04 18:27 UTC, fawaz-ahmed commented on example/src/modules/ImageCrush.js
> +        if (!d.type.includes('image')) {
Why have we added this block ?

2022-04-04 18:27 UTC, fawaz-ahmed commented on example/src/modules/ImageCrush.js
> +  return <img className={'fade-in-Image'} src={image} {...props} />;
class name should come as prop and be able to override like other props

2022-04-04 18:27 UTC, fawaz-ahmed commented on example/src/modules/ErrorRender/ErrorRender.js
> +            <span className="front text"> retry
Remove text, since text has to be localized

2022-04-06 18:52 UTC, assetcrush commented on README.md
> +      <ImageCrush onLoad={onLoad} onError={onError} url={testUrl} width={50} height={50} />
Remove `onLoad={onLoad} onError={onError}` from Usage, only add in props table

2022-04-06 18:52 UTC, assetcrush commented on README.md
> +      <ImageCrushAdoptive onLoad={onLoad} onError={onError} url={testUrl} />
same here

2022-04-06 18:53 UTC, assetcrush commented on example/src/modules/ErrorRender/ErrorRender.js
> +        <span style={{color: reloadIconColor,fontSize: height / 2}} onClick={_handleRetry} className="reload">
Indent please

2022-04-06 18:54 UTC, assetcrush commented on README.md
> +      <ImageCrush  url={testUrl} width={50} height={50} />
Extra space befor `url`

2022-04-06 18:54 UTC, assetcrush commented on README.md
> +      <ImageCrushAdoptive  url={testUrl} />
Remove extra space before url

2022-04-06 18:55 UTC, assetcrush commented on README.md
> +| `isSpinner` | `bool` | no       | render spinner while image loads or not |
isSpinner is not accurate, change it to `hideSpinner`

2022-04-06 18:55 UTC, assetcrush commented on README.md
> +| `onError` | `func` | no       | if image fails to load (returns error details) |
onError and onLoad are repeating

2022-04-06 18:56 UTC, assetcrush commented on example/src/App.js
> +    <div style={{ width: 50, height: 50 }}>
Better not change this width and height

2022-04-06 18:57 UTC, assetcrush commented on example/src/modules/ImageCrush.js
> +  if (image)
is this condition correct ? maybe there should be a `!`

2022-04-06 18:58 UTC, assetcrush commented on example/src/modules/ImageCrush.js
> +      <>{isSpinner && <Spinner icon={spinnerIcon} color={spinnerColor} />}</>
Do we need this fragment, if not remove it

2022-04-06 18:59 UTC, assetcrush commented on example/src/modules/Spinner/styles.css
> +/* .lds-roller div:after {
remove commented css

2022-04-06 19:03 UTC, assetcrush requested changes
See comments

2022-04-06 19:25 UTC, assetcrush commented on README.md
> +Any additional props are passed down to underlying `<ImageCrush />` component.
underlying is img component

2022-04-06 19:26 UTC, assetcrush commented on README.md
> +| `isSpinner` | `bool` | no       | render spinner while image loads or not |
Please rename this to `hideSpinner`

2022-04-06 19:27 UTC, assetcrush commented on README.md
> +| `wrapperStyle` | `object` | no       | style object for outermost div |
All the ImageCrush props should also be part of ImageCrushAdoptive component

2022-04-06 19:29 UTC, assetcrush requested changes
Still changes needed

2022-04-06 19:29 UTC, assetcrush commented on example/src/modules/Spinner/styles.css
> +/* .assetcrush-lds-roller div:after {
remove commented css

2022-04-07 16:54 UTC, assetcrush commented on example/src/modules/ImageCrush.js
> +  }, [setIsError]);
Dependency will be `fetchImage` and move this function below fecthImage

2022-04-07 16:55 UTC, assetcrush commented on example/src/modules/Spinner/Spinner.js
> +const styles = (backgroundColor) =>  ({
remove this, since not used

2022-04-07 16:55 UTC, assetcrush requested changes
Overall PR looks good, just some minor issues

2022-04-07 17:02 UTC, assetcrush approved these changes

2022-04-07 17:02 UTC, merged